version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-mem0
    ports:
      - "6379:6379"  # Redis port
      - "8001:8001"  # RedisInsight web UI
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
    driver: local